### ISSUE TITLE
Make scripts available

### ISSUE THREAD

**Issue by andrew01144** [andrew01144/Tasmota-SomfyRTS#1]
@Chaosflori25 Does this README answer your questions?

**Comment by Chaosflori25** [comment]
@andrew01144 Yes, one question I did not ask: Can you also make a Version for the ESP 8266/NodeMCU?

**Comment by andrew01144** [comment]
> @andrew01144 Yes, one question I did not ask: Can you also make a Version for the ESP 8266/NodeMCU?

No. It is written in Berry, and Berry is only available on Tasmota32.

**Comment by Chaosflori25** [comment]
And then it would be nice if you can upload the scripts. I can only test them later, since I have to search my esp32

**Comment by andrew01144** [comment]
> And then it would be nice if you can upload the scripts. I can only test them later, since I have to search my esp32

Will do. Let me know how you get on.

**Comment by ruedli** [comment]
hooking up my CC1101 to a working tamota32-ir.bin firmware. I noticed you are not using GDO2. I am not sure if this is needed, probably not as I read in the module documentation:

![image](https://user-images.githubusercontent.com/5008440/194700026-8d37d68d-e5af-4837-9b31-7a0987ba03e8.png)

Was it used in the CC1101 library and were we not depending on that part of it for sending Somfy commands? If so might be worse documenting in the Berry script. You mentioned you needed to hookup 8 wires between module and ESP32, but like this there are only 7 wires needed. Or did you hook it up somewhere that I cannot see from the script?

**Comment by andrew01144** [comment]
Scripts uploaded to github - issue closed.
