### ISSUE TITLE
RFtxSMFY Command Unknown

### ISSUE THREAD

**Issue by darenkeates** [andrew01144/Tasmota-SomfyRTS#3]
Hi,
I've included the console window from boot to me entering the 'rolling code' statement which it doesn't recognise? I thought I'd found it when I realised I'd mis-spelt 'autoexec' der! but it wasn't that. Any ideas please??

00:00:00.003 HDW: ESP32-D0WD-V3 
00:00:00.018 UFS: FlashFS mounted with 280 kB free
00:00:00.039 CFG: Loaded from File, Count 82
00:00:00.055 QPC: Count 1
00:00:00.060 SPI: Software using GPIO18(CLK), GPIO23(MOSI) and GPIO19(MISO)
00:00:00.134 BRY: Berry initialized, RAM used=3089 bytes
00:00:00.154 Project tasmota - Tasmota Version 12.1.1(ir)-2_0_4_1(2022-08-25T11:34:03)
00:00:00.723 WIF: Connecting to AP1 NE55 Channel 1 BSSId 20:B0:01:CE:A0:FB in mode 11n as tasmota-6040...
00:00:02.678 WIF: Connected
21:08:20.017 HTP: Web server active on tasmota-6040 with IP address 192.168.1.20
21:08:21.927 MQT: Attempting connection...
21:08:21.959 MQT: Connected
21:08:21.965 MQT: tasmota/somfy/LWT = Online (retained)
21:08:21.969 MQT: tasmota/somfy/cmnd/POWER = 
21:08:21.974 MQT: tasmota/somfy/INFO1 = {"Info1":{"Module":"ESP32-DevKit","Version":"12.1.1(ir)","FallbackTopic":"cmnd/DVES_D37798_fb/","GroupTopic":"tasmota/somfy/cmnd/"}}
21:08:21.990 MQT: tasmota/somfy/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"tasmota-6040","IPAddress":"192.168.1.20"}}
21:08:22.005 MQT: tasmota/somfy/INFO3 = {"Info3":{"RestartReason":"Software reset CPU","BootCount":11}}
21:08:22.022 MQT: tasmota/somfy/RESULT = {"POWER1":"OFF"}
21:08:22.025 MQT: tasmota/somfy/POWER1 = OFF
21:08:22.028 MQT: tasmota/somfy/RESULT = {"POWER2":"ON"}
21:08:22.031 MQT: tasmota/somfy/POWER2 = ON
21:08:22.033 MQT: tasmota/somfy/RESULT = {"POWER3":"ON"}
21:08:22.046 MQT: tasmota/somfy/POWER3 = ON
21:08:22.049 MQT: tasmota/somfy/RESULT = {"POWER4":"ON"}
21:08:22.051 MQT: tasmota/somfy/POWER4 = ON
21:08:24.964 QPC: Reset
21:08:25.965 MQT: tasmota/somfy/STATE = {"Time":"2022-10-11T21:08:25","Uptime":"0T00:00:09","UptimeSec":9,"Heap":164,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Berry":{"HeapUsed":3,"Objects":32},"POWER1":"OFF","POWER2":"ON","POWER3":"ON","POWER4":"ON","Wifi":{"AP":1,"SSId":"NE55","BSSId":"20:B0:01:CE:A0:FB","Channel":1,"Mode":"11n","RSSI":96,"Signal":-52,"LinkCount":1,"Downtime":"0T00:00:03"}}
21:08:26.009 MQT: tasmota/somfy/SENSOR = {"Time":"2022-10-11T21:08:25","ESP32":{"Temperature":23.3},"TempUnit":"C"}
21:09:18.806 CMD: RFtxSMFY {"Idx":1,"Id":123,"RollingCode":1}
21:09:18.819 MQT: tasmota/somfy/RESULT = {"Command":"Unknown"}

**Comment by andrew01144** [comment]
The autoexec.be file is not present. You should not need to type the name, you just need to select it in the upload file chooser.

1) Download autoexec.be and RFtxSMFY.be from this github project onto you PC.
2) Edit RFtxSMFY.be on your PC: Change the CC1101 line to enable it.
3) Upload autoexec.be and RFtxSMFY.be from your PC to the Tasmota filesystem. Do that by...
Go to the Tasmota WebUI.
Consoles
Manage File system
Choose File (choose autoexec.be on your PC)
Start Upload
Choose File (choose RFtxSMFY.be on your PC)
Start Upload
Console
Main Menu
Restart

That should do it.
My console looks like this:

00:00:00.727 Project tasmota - esp32-dev-01 Version 12.1.1(custom-ir)-2_0_4_1(2022-10-08T13:51:49)
00:00:01.842 BRY: Successfully loaded 'autoexec.be'   <<<< Important!
00:00:03.174 WIF: Connecting to AP1 HFC046 Channel 1 BSSId 74:83:C2:91:4A:AC in mode 11n as esp32-dev-01...
00:00:05.214 WIF: Connected
00:00:05.476 HTP: Web server active on esp32-dev-01 with IP address 192.168.1.118
21:55:10.367 MQT: Attempting connection...
21:55:10.402 MQT: Connected

**Comment by andrew01144** [comment]
The next problem you will have is the SPI assignments.
You have assigned the SSPI pins, my code expects the SPI pins. Double check the pulldown GPIO menu and you will see what I mean.

(you may have a point - maybe I should look for the SSPI pins. I'll think about that. But for now, you need to assign the SPI pins).

**Comment by darenkeates** [comment]
I still cannot get the autoexec.be to run so have to load the file in the Berry console to get it to work.
You are then absolutely correct it throws an error about the SSPI pins but my drop down doesn't have SPI options
***@***.***



Regards

Daren Keates MSc
Principal Project Engineer - New Technology

Siemens Mobility Limited
Station Approach, Swanley, Kent, BR8 8JD, UK.
Mobile: +44 (0) 7921 247 011
Email: ***@***.******@***.***>
***@***.***

**Comment by andrew01144** [comment]
That is odd. I don't know why your experience is different than mine.
What is the product name of ESP32 module you have?
At the top of the Configure Module menu, what is the "Module type"?
Can you show me a screen grab of the Manage File system page? It should look like this:

![image](https://user-images.githubusercontent.com/18399286/195384527-f2f8de80-af7b-42fc-8945-0ed58cb68314.png)
(though you will not have RFtxOther.be on yours)

In the meantime
Edit RFtxSMFY.be, and change the 4 lines with SPI_ to SSPI_ (like below).
Continue to load("autoexec.be") if that works for you.

Change this:
    SCK_PIN  = gpio.pin(gpio.SPI_CLK)
    MISO_PIN = gpio.pin(gpio.SPI_MISO)
    MOSI_PIN = gpio.pin(gpio.SPI_MOSI)
    CS_PIN   = gpio.pin(gpio.SPI_CS)
To this:
    SCK_PIN  = gpio.pin(gpio.SSPI_SCLK)          # Note this is SCLK, not CLK !!
    MISO_PIN = gpio.pin(gpio.SSPI_MISO)
    MOSI_PIN = gpio.pin(gpio.SSPI_MOSI)
    CS_PIN   = gpio.pin(gpio.SSPI_CS)
   print("Configuring gpio pins")    # Some debug is always useful!

**Comment by darenkeates** [comment]
Hi,
Please see screen shots attached. My ESP32 device is made by WROOM if that makes a difference?
I've tried loading various Tasmota images and ended up with the tasmota32-ir.bin V12.0.2.

I'm guessing the reason there isn't an autoexec.bec is because it is not running by itself, I still have to load the RFtxSMFY.be file manually.

***@***.******@***.***


Regards

Daren Keates MSc
Principal Project Engineer - New Technology

Siemens Mobility Limited
Station Approach, Swanley, Kent, BR8 8JD, UK.
Mobile: +44 (0) 7921 247 011
Email: ***@***.******@***.***>
***@***.***

**Comment by andrew01144** [comment]
I can't see the images on my email or on the github page.
Please respond using the github page, and paste the image into the Write window. That works for me.

There is something very odd about this.
FYI - the .bec is the compiled version of the .be.
So, if I delete RFtxSMFY.bec in the Manage File system page (click the burn icon), then load("RFtxSMFY.be") in the Berry console, RFtxSMFY.bec reappears on the Manage File system page.

**Comment by darenkeates** [comment]
I have now got the SPI part working by downloading your Tasmota image rather than one of the web.

It still doesn't load the autoexec so I load manually.

![image](https://user-images.githubusercontent.com/33462167/195397445-83cd756d-e808-45aa-8867-a86e0a979ca7.png)

![image](https://user-images.githubusercontent.com/33462167/195397528-87b5fbff-246f-4bfa-b0f9-8e5a0a5ef149.png)

**Comment by andrew01144** [comment]
Your autoexec.be starts with an uppercase A !

Do any of the RFtxSMFY commands work?

**Comment by andrew01144** [comment]
SPI vs SSPI: thanks for discovering this. tasmota32.bin has SPI, as does by customer build. But you are correct: tasmota32-ir.bin does not have SPI. I will change my code at some point to use SSPI.
(though you will need my custom build, or your own similar custom build, when/if you want to try the Tasmota Shutter commands, like ShutterOpen, ShutterClose, etc)

**Comment by darenkeates** [comment]
Oh wow! Thanks.

Regards

Daren Keates MSc
Principal Project Engineer - New Technology

Siemens Mobility Limited

Station Approach, Swanley, Kent, BR8 8JD, UK.
Mobile: +44 (0) 7921 247 011<tel:+44%207921%20247%20011>
E ***@***.******@***.***>


On 12 Oct 2022, at 17:30, andrew01144 ***@***.***> wrote:

﻿

Your autoexec.be starts with an uppercase A !

**Comment by darenkeates** [comment]
Couldn’t wait until tomorrow to try it and I’m not sure how you noticed it but wow! Everything works and my blinds move in and out.
Thank you.
I just need to work out how to get my Hubitat to talk to it. I’m guessing it’ll have to be MQTT so I’ll need to learn that next.
Brilliant

Regards

Daren Keates MSc
Principal Project Engineer - New Technology

Siemens Mobility Limited

Station Approach, Swanley, Kent, BR8 8JD, UK.
Mobile: +44 (0) 7921 247 011<tel:+44%207921%20247%20011>
E ***@***.******@***.***>


On 12 Oct 2022, at 17:30, andrew01144 ***@***.***> wrote:

﻿

Your autoexec.be starts with an uppercase A !

**Comment by andrew01144** [comment]
That's excellent, I'm so glad it works for you!

A few things to think about:
1) If Hubitat and mqtt looks difficult, you could try getting Hubitat to send http commands. Tasmota prefers mqtt, but it can be used with http.
    eg: ```curl -s --data-urlencode 'cmnd=RFtxSMFY {"Idx":1,"Button":2}' http://192.168.1.123/cm```
    or put this in your browser ```http://192.168.1.123/cm?cmnd=RFtxSMFY%20%7B%22Idx%22%3A1%2C%22Button%22%3A2%7D```
Let me know if you want me to explain any of that.

2) An optional Tasmota step... Currently, you can send Up and Down commands. If you setup Tasmota Shutters, you should be able to say ```ShutterPosition 30``` to send the blind to 30% open. See [here](https://github.com/andrew01144/Tasmota-SomfyRTS/blob/main/README.md#integration-with-tasmota-shutters-and-blinds). You won't need to build a custom tasmota binary because you used my custom binary.

3) Pretty soon, I'll change RFtxSMFY.be to use the SSPI pins instead of SPI. I'll tell you when, and you should probably update your system.

**Comment by andrew01144** [comment]
@darenkeates @ruedli
I have updated RFtxSMFY.be (and README.md) to use SSPI instead of SPI GPIOs.
Please download the new version. Remember to edit the ```hasCC1101``` and ```tasmotaShutterIntegration``` lines to match your current configs. Upload the file to Tasmota, go to Configure Module, and change the assigned SPI pins to SSPI pins.

I did this because:
- @darenkeates pointed out that SPI is not available in tasmota32-ir.bin, so my README does not work.
- SSPI is more appropriate, because this is a Software SPI implementation.

@ruedli - many thanks for your kind words, and you are welcome!

**Comment by darenkeates** [comment]
Updated to the new SSPI, all good thank you. 
I have also taken your suggestion and used http GET calls rather than delve into MQTT for just this one function. I have built a driver in Hubitat to make the calls:=
![image](https://user-images.githubusercontent.com/33462167/195635013-0b3f1594-b3cd-4f69-9115-9bbd45efa67d.png)
Thanks for your help

**Comment by andrew01144** [comment]
Oh, very good!
