### ISSUE TITLE
Tasmota shutter limit

### ISSUE THREAD

**Issue by prbtt** [andrew01144/Tasmota-SomfyRTS#5]
First things first, I'd like to congradulate you for this amazing project. It worked flawlessly!

I only have one question though. Is it possible to remove the only 4 shutter limit from tasmota? As soon as I typed shutterrelay5 9 I got "command error". All the previous 4 worked fine.

**Comment by andrew01144** [comment]
Thanks @prbtt, I'm glad it worked for you.

Are more than 4 shutters supported?
I don't know, this is a Tasmota question, and you need to direct your question to one of their forums.
I took a quick look in the [source](https://github.com/arendst/Tasmota/blob/development/tasmota/tasmota_xdrv_driver/xdrv_27_shutter.ino), and there is a constant MAX_SHUTTERS. I tried compiling tasmota with MAX_SHUTTERS 5, and it gave an error during build: "TSettings Size is not correct", so it's clearly not as easy as that. However, it may be possible if you know how.

You can, of course, support more Somfy blinds if you don't use Tasmota Shutters, but you would need to do more work on your host system. That's easy enough if you just want open and close, but more complex if you need to calculate travel-times to "open 50%" etc.

Details: Using [TasmoCompiler](https://gitpod.io/#https://github.com/benzino77/tasmocompiler), I added "#define MAX_SHUTTERS 5" to "Custom Parameters".

**Comment by prbtt** [comment]
> Thanks @prbtt, I'm glad it worked for you.
> 
> Are more than 4 shutters supported? I don't know, this is a Tasmota question, and you need to direct your question to one of their forums. I took a quick look in the [source](https://github.com/arendst/Tasmota/blob/development/tasmota/tasmota_xdrv_driver/xdrv_27_shutter.ino), and there is a constant MAX_SHUTTERS. I tried compiling tasmota with MAX_SHUTTERS 5, and it gave an error during build: "TSettings Size is not correct", so it's clearly not as easy as that. However, it may be possible if you know how.
> 
> You can, of course, support more Somfy blinds if you don't use Tasmota Shutters, but you would need to do more work on your host system. That's easy enough if you just want open and close, but more complex if you need to calculate travel-times to "open 50%" etc.
> 
> Details: Using [TasmoCompiler](https://gitpod.io/#https://github.com/benzino77/tasmocompiler), I added "#define MAX_SHUTTERS 5" to "Custom Parameters".

Thanks a lot!

Is there any limit for how many somfy blinds I can add without the tasmota shutter mode? Because I might just make the time based covers in home assistant and use the open/close/stop commands to trigger them.

**Comment by andrew01144** [comment]
In 'stateless mode', there is no limit, but you need to maintain the rolling code yourself.
In 'stateful mode', there is a limit of 8, but this is easily increased by editing the Berry code. IIRC, just add some more initializations to the line containing persist.sState = [[0,0],[0,0]... .
The difference between sateful and stateless should be clear in the [RFtxSMFY description]( https://github.com/andrew01144/Tasmota-SomfyRTS#the-rftxsmfy-command).

Depending how good HA's support for blinds is, you may find that more convenient than using tasmota.

**Comment by andrew01144** [comment]
@prbtt - just for my interest... Which transmit module are you using, and how many blinds do you want to control?

**Comment by prbtt** [comment]
> @prbtt - just for my interest... Which transmit module are you using, and how many blinds do you want to control?

I'm using the C1101 and there's probably over 16 blinds, but I'll group them with the somfy remote and just use 6 or 7 channels, since there is no use in operating them separately. Just need them to open and close daily to avoid the sun burning furniture. If the esp32 is capable of 16 channels with stateful mode, that will be very useful in the future.
Have you tried this same solution but using esphome instead?
![16731798393689033055131974096004](https://user-images.githubusercontent.com/60021461/211195320-f43d0e5f-ba9a-4324-a713-01bd1ade1555.jpg)

**Comment by andrew01144** [comment]
Thanks for sharing - that's very impressive. I'm proud to contribute to it :-)
I don't use Home Assistant, so Tasmota is more suitable for me than ESPHome.
Before Tasmota, I used an ESP8266 running my own code since May 2018. However, I wanted to replace all the devices running  my own code with Tasmota because it's easier to maintain. Hence, this Berry implementation.
It looks like someone has done [Somfy for ESPHome](https://github.com/dmslabsbr/esphome-somfy).

**Comment by purche42** [comment]
Great Work . I have tested shutters with my working Pi-Somfy IDs and rolling codes. All works fine without new learning of shutters. I also have added a 9th shutter. 
Unfortunately there is a '4 shutter' limitation of Tasmota's support for Shutters and Blinds. Probably Theo Arends will raise the limit for ESP32 devices.

**Comment by andrew01144** [comment]
@purche42 Thanks for your message. It's always nice to hear of successful implementations!
